version: '3'

services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80

  db:
    image: mariadb:10.3
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_crud
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

volumes:
  db_data: